### PR TITLE
Fix manual installation instructions

### PR DESCRIPTION
**Pull request by warpling**
After many hours and the help of some friends I discovered the missing steps necessary to compile this library. Hopefully adding these can help save future devs some time and clarify how to use the library alongside Cocoapods :)

### CODE REVIEW

**Comment by msanders** [comment]
@warpling Sorry to hear that - thanks for adding clarification to the install instructions. I'll look into adding CocoaPods support if it makes installation easier for everyone familiar with it. Glad to hear you're interested in the library! Let me know if you have any other feedback.

**Comment by warpling** [comment]
Thanks for the quick merge @msanders. While I was able to get it to compile, I wasn't able to get it to run on device until just now due to the depended upon frameworks (`Result.framework`, etc) so I'm afraid these instructions still are not complete…

It seems the final necessary step might have been to manually include the 5 dependencies of TrueTime (in addition to `TrueTime.framework`) in the *Embed Frameworks* step in *Build Phases*. Sound right?
```
dyld: Library not loaded: @rpath/Result.framework/Result
  Referenced from: /private/var/containers/Bundle/Application/8F4E6430-AE7C-4FCF-A6E7-D49ADE75A94A/MyApp.app/Frameworks/TrueTime.framework/TrueTime
  Reason: image not found
```

**Comment by msanders** [comment]
Ah, good point. It should only be necessary to link with `Result.framework` (the others are just used for tests), but that step is currently missing from the README. I believe you can also install this as a CocoaPod.

FWIW, I highly recommend trying out [Carthage](https://github.com/Carthage/Carthage) - it's possible to use this alongside Cocoapods, as it doesn't interfere with the project file, etc.

**Comment by warpling** [comment]
My project is in Obj-C and has dozens of dependencies so switching isn't an easy option, *but* I will definitely re-try it with Carthage if they can work side-by-side. Might be worth adding that to the README too?

**Comment by msanders** [comment]
:+1: totally, thanks for the feedback. You should be able to get it working by following the steps listed [here](https://github.com/instacart/TrueTime.swift#carthage) and [here](https://github.com/Carthage/Carthage#adding-frameworks-to-an-application). Basically, just need to:

- Add a `Cartfile` in your repo containing `instacart/TrueTime.swift`.
- Run `carthage bootstrap` (which should implicitly build both `TrueTime` and `Result`).
- Add a separate build phase to link `TrueTime` and `Result`.

**Comment by warpling** [comment]
Could you clarify that last step? I assume you mean adding `TrueTime.framework` and `Result.framework` to **Link Binary With Libraries**?

**Comment by msanders** [comment]
Yep, just add a `Run Scripts` phase with the `copy-frameworks` script shown on [step number 4](https://github.com/Carthage/Carthage#adding-frameworks-to-an-application) in the above link (which should be the same as a Link Binary With Libraries step only it adds a workaround for an app store submission bug).

**Comment by warpling** [comment]
Got it working thank you!! Fingers crossed it works for submission too.
(This sort of minutia is admittedly why I use pods; I like to be hands-off my build system as I tend to break it. 😅)

**Pull request merged**
